### ISSUE TITLE
Ignore objects with non latin keys

### ISSUE THREAD

**Issue by gendalf** [puleos/object-hash#37] opened 2016-07-29 17:20 UTC
Objects like 
{ 'ключ': 'значение' }
and
{ 'ключ': 'значение1' }

Have same hash result

**Comment by addaleax** [comment] 2016-07-30 06:25
Can you show e.g. a piece of code to reproduce this? This is the result for me:

```
> hash({ 'ключ': 'значение' })
'41d5ec33452b20881f7c91709c882f97a2d9d514'
> hash({ 'ключ': 'значение1' })
'4c6f4c8fbad4a7491f529442f15bd128f4a22b12'
```

**Comment by addaleax** [comment] 2016-08-01 19:12
@gendalf If that didn’t answer your question… are you asking to have these kinds of keys to be ignored? Or what exactly is the behaviour you are seeing/would like to see?

**Comment by bean5** [comment] 2017-09-14 00:17
@addaleax if the has function were to ignore those _keys_, the objects would each basically be `{ }`, so the above two objects would have equivalent hash values.

So you could reword this request as:
> Please add a flag to ignore non-latin keys such that the following test case passes:
> `assertTrue(hash({ 'ключ': 'значение' }) === hash({ 'ключ': 'значение1' }))`

Is that correct, @gendalf ?

**Comment by addaleax** [comment] 2017-09-14 09:01
I think a feature ignoring non-latin keys is something I’d like to avoid, because it seems a lot more specific than what this library is trying to achieve. You can already pass a `replacer` function with which you can transform the individual bits of input, and I think that could be used for stripping these properties as well:

```js
const hash = require('object-hash');
function customHash(val) {
  return hash(val, {
    replacer(value) {
      if (typeof value === 'object') {
        return Object.assign(Object.create(null), ...Object.keys(value).map(
          key => /^[\u0000-\u00ff]*$/.test(key) ? { [key]: value[key] } : {}
        ));
      }
    }
  });
}

console.log(customHash({}))
  // => 06544744aa250bb687c9fc0de3355ff875d0499d
console.log(customHash({'foo': 'bar'}))
  // => e736de6493b799a5074d9de22ee485b3f9b44700
console.log(customHash({'foo': 'bar', 'ключ': 'значение'}))
  // => e736de6493b799a5074d9de22ee485b3f9b44700
```

**Comment by bean5** [comment] 2017-09-14 13:11
That is a valid point. Might be worth mentioning some use cases for replacer such as this one in the documentation.

**Comment by addaleax** [comment] 2017-09-14 13:13
@bean5 In that case, can you explain what the use case for this is? :)

**Comment by bean5** [comment] 2017-09-14 13:15
"removing keys that have non-latin characters" ?

**Comment by addaleax** [comment] 2017-09-14 13:17
@bean5 yeah, but that’s an action, not a use case? like, why/for what do you want to do this?

**Comment by bean5** [comment] 2017-09-14 16:05
Sorry, didn't get trained 100% in differentiating those two. I think you can close this now. Sounds like your aren't amenable to adding documentation or code. I can't speak for they original use case. I mainly wanted to clarify the ask as I understood it.

**Comment by addaleax** [comment] 2017-09-14 16:12
@bean5 Okay, thanks. And re: adding documentation code – I would be perfectly okay with that if I could know why somebody might want to do this? It doesn’t seem to be useful to a lot of people to dismiss keys based on their character code ranges…

(Also: PRs are generally welcome!)

**Closed by addaleax** 2017-09-14 16:12 UTC
