### ISSUE TITLE
Error: Algorithm "sha1" not supported. supported values: passthrough

### ISSUE THREAD

**Issue by ccorcos** [puleos/object-hash#41] opened 2016-11-30 18:14 UTC
I originally posted this on the `eslint-loader` project https://github.com/MoOx/eslint-loader/issues/128

```
Module build failed: Error: Algorithm "sha1"  not supported. supported values: passthrough
  at applyDefaults (/Users/chet/Code/doug/packages/doug/node_modules/object-hash/index.js:89:11)
  at objectHash (/Users/chet/Code/doug/packages/doug/node_modules/object-hash/index.js:31:13)
  at Object.module.exports (/Users/chet/Code/doug/packages/doug/node_modules/eslint-loader/index.js:155:20)
```

No idea what thats all about:

```
~ ❯❯❯ node --version
v6.3.1
~ ❯❯❯ node
> crypto.getHashes()
[ 'DSA',
  'DSA-SHA',
  'DSA-SHA1',
  'DSA-SHA1-old',
  'RSA-MD4',
  'RSA-MD5',
  'RSA-MDC2',
  'RSA-RIPEMD160',
  'RSA-SHA',
  'RSA-SHA1',
  'RSA-SHA1-2',
  'RSA-SHA224',
  'RSA-SHA256',
  'RSA-SHA384',
  'RSA-SHA512',
  'dsaEncryption',
  'dsaWithSHA',
  'dsaWithSHA1',
  'dss1',
  'ecdsa-with-SHA1',
  'md4',
  'md4WithRSAEncryption',
  'md5',
  'md5WithRSAEncryption',
  'mdc2',
  'mdc2WithRSA',
  'ripemd',
  'ripemd160',
  'ripemd160WithRSA',
  'rmd160',
  'sha',
  'sha1',
  'sha1WithRSAEncryption',
  'sha224',
  'sha224WithRSAEncryption',
  'sha256',
  'sha256WithRSAEncryption',
  'sha384',
  'sha384WithRSAEncryption',
  'sha512',
  'sha512WithRSAEncryption',
  'shaWithRSAEncryption',
  'ssl2-md5',
  'ssl3-md5',
  'ssl3-sha1',
  'whirlpool' ]
```

**Comment by addaleax** [comment] 2016-12-01 13:34
This seems weird. Could you show instructions for reproducing the original error you are seeing?

Also, does `npm ls|grep object-hash` give you the latest version of `object-hash` (1.1.5)?

**Comment by ccorcos** [comment] 2016-12-01 22:03
yes, 1.1.5

you can see if you can reproduce it on your end (the sed command enables eslint which is using object hash [here](https://github.com/MoOx/eslint-loader/blob/672a1008e29162b03e82519df7bab30f27923e69/index.js#L43)):

```sh
cd /tmp
git clone git@github.com:ccorcos/doug.git
npm install --global lerna@prerelease
cd doug
lerna bootstrap
cd packages/doug-app/webpack
sed -i '' -e 's/\/\/ require/require/g' base.js
cd ../../example-app
npm start
```

You can see the result when I run the following:

https://gist.github.com/ccorcos/4fdbc1416111506299234be538ac30e6

**Comment by addaleax** [comment] 2016-12-01 23:56
You are experiencing https://github.com/montagejs/collections/issues/162, this has nothing to do with `object-hash`. The `collections` module is overriding language built-ins like `Array.from`, which is something you are *never* supposed to do (and issues like this are the reason for that).

The dependency chain for that is `doug → gh-pages → q-io → collections`.
I don’t know what options you have here, but you are pretty much stuck with patching `collections` yourself, lobbying really hard for that issue to get fixed, or removing one dependency in that chain.
There is an issue at https://github.com/tschaub/gh-pages/issues/42, so if you want to work on that, I’d suggest doing it at the `gh-pages` level.

I’m closing this as it’s not an issue with `eslint-loader` or `object-hash`; feel free to ask any follow-up questions, though.

**Closed by addaleax** 2016-12-01 23:56 UTC

**Comment by ccorcos** [comment] 2016-12-02 00:07
thank you so much for the help! that's so annoying -- this is a perfect example of why you shouldnt override prototypes.

**Comment by ccorcos** [comment] 2016-12-02 00:14
also, how did you find that?

**Comment by addaleax** [comment] 2016-12-02 03:00
> also, how did you find that?

So… I looked up the script that was actually getting executed (I think that was `packages/example-app/node_modules/.bin/doug-app`) and had a kinda good idea of what the problem was, judging from your report. I felt like `crypto.getHashes()` got overwritten or mocked or whatever, so what I did was I insert a `console.log(require('crypto').getHashes().includes('sha1'))` line, once at the beginning of the file and once at the end of the file.
When placing that line at the beginning it gave `true`, at the end it gave `false`, so that seemed to support my first idea, and from there on I “bisected” through the statements by moving the `console.log` around, and following the `require`s that appeared to be responsible.
And yeah, once I had narrowed it down to the overwritten `Array.from` being responsible, I just inserted a `console.trace(values)` in there, and that pretty much confirmed that that kind of shimming did not work well…

**Comment by ccorcos** [comment] 2016-12-02 19:51
Oh interesting. `console.trace(values)` -- is that going to log the stack trace of where that variable is passed?!

**Comment by addaleax** [comment] 2016-12-02 20:29
`console.trace(values)` is basically just `console.log(values)` + `console.log(new Error().stack)` – nothing too fancy. :smile:

**Comment by fo2w** [comment] 2017-03-13 04:32
same issue, is there a solution?

**Comment by addaleax** [comment] 2017-03-13 13:03
@fo2w Can you give more details, like a reproduction, or the output of `npm ls`?

**Comment by d-a-g-e** [comment] 2017-11-08 20:45
`Error: Algorithm "md5"  not supported. supported values: passthrough`
this work form me D:
`hash(obj, { algorithm: 'passthrough' }`
